services:
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
      args:
        - PYTHON_VERSION=3.14.3
        - APP_PORT=8080
        - API_URL=http://localhost:8000
        - LOG_LEVEL=debug
    container_name: querymind-ui-314
    ports:
      - "8080:8080"
      - "8000:8000"